# Generated by Django manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerank_users', '0001_initial'), # Depends on the UserProfile migration
    ]

    operations = [
        migrations.CreateModel(
            name='SitePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ] 